---
- name: Install Prometheus
  hosts: "servers"
  become: yes
  tasks:
    - name: Create Prometheus user
      user:
        name: prometheus
        shell: /bin/false

    - name: Download Prometheus
      get_url:
        url: "{{prometheus_release}}"
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move Prometheus binaries
      command: >
        mv /tmp/prometheus-2.44.0.linux-amd64/prometheus /usr/local/bin/
      become: yes

    - name: Move Promtool binary
      command: >
        mv /tmp/prometheus-2.44.0.linux-amd64/promtool /usr/local/bin/
      become: yes

    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Move Prometheus config
      command: >
        mv /tmp/prometheus-2.44.0.linux-amd64/prometheus.yml /etc/prometheus/
      become: yes
      
    - name: Create Prometheus systemd service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus/ \
            --web.console.templates=/etc/prometheus/consoles \
            --web.console.libraries=/etc/prometheus/console_libraries

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start and enable Prometheus service
      systemd:
        name: prometheus
        enabled: yes
        state: started
