---
- name: Install Prometheus
  hosts: "servers"
  become: true
  tasks:
    - name: Create Prometheus user
      ansible.builtin.user:
        name: prometheus
        shell: /bin/false

    - name: Download Prometheus
      ansible.builtin.get_url:
        url: "{{prometheus_release}}"
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      ansible.builtin.unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move Prometheus binaries
      ansible.builtin.command: >
        mv /tmp/prometheus-2.44.0.linux-amd64/prometheus /usr/local/bin/
      become: true

    - name: Move Promtool binary
      ansible.builtin.command: >
        mv /tmp/prometheus-2.44.0.linux-amd64/promtool /usr/local/bin/
      become: true

    - name: Create Prometheus directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Move Prometheus config
      ansible.builtin.command: >
        mv /tmp/prometheus-2.44.0.linux-amd64/prometheus.yml /etc/prometheus/
      become: true
      
    - name: Create Prometheus systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus/ \
            --web.console.templates=/etc/prometheus/consoles \
            --web.console.libraries=/etc/prometheus/console_libraries

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable Prometheus service
      ansible.builtin.systemd:
        name: prometheus
        enabled: yes
        state: started
