# based on https://www.atlantic.net/vps-hosting/how-to-install-consul-server-on-ubuntu/
- name: Install consul single instance
  hosts: servers
  tasks:
    - name: Update apt
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Install unzip gnupg2 curl wget
      become: true
      ansible.builtin.apt:
        name:
          - unzip
          - gnupg2
          - curl
          - wget
        state: present
        update_cache: true

    - name: Download consul release
      ansible.builtin.get_url:
        url: "{{ consul_release }}"
        dest: /tmp/{{ consul_zip_file }}
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: '755'

    - name: Extract
      ansible.builtin.unarchive:
        src: /tmp/{{ consul_zip_file }}
        dest: /tmp/
        remote_src: true

    - name: Copy consul binary to /usr/local/bin
      become: true
      ansible.builtin.copy:
        src: /tmp/{{ consul_file }}
        dest: /usr/local/bin/{{ consul_file }}
        mode: '0755'

    - name: Remove consul binary from /tmp
      become: true
      ansible.builtin.file:
        path: /tmp/{{ consul_file }}
        state: absent

    - name: Create consul group
      become: true
      ansible.builtin.group:
        name: "{{ consul_group }}"
        state: present

    - name: Create consul user
      become: true
      ansible.builtin.user:
        name: "{{ consul_user }}"
        group: "{{ consul_group }}"
        state: present
        createhome: true
        home: /home/{{ consul_user }}
        shell: /bin/bash

    - name: Create directories
      become: true
      ansible.builtin.file:
        dest: "{{ item }}"
        state: directory
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: '755'
      with_items:
        - /var/lib/consul
        - /etc/consul.d

    - name: Copy consul systemd service file
      become: true
      ansible.builtin.copy:
        src: ./files/consul.service
        dest: /etc/systemd/system/
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: '755'

    - name: Reload systemd
      become: true
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Copy consul config file
      become: true
      ansible.builtin.copy:
        src: ./files/config.json
        dest: /etc/consul.d/config.json
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: '755'

    - name: Set secret
      become: true
      ansible.builtin.lineinfile:
        path: /etc/consul.d/config.json
        regexp: '"encrypt": "key"'
        line: '"encrypt": "{{ consul_encrypt_key }}"'

    - name: Change owner for created directories and files
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: '755'
      with_items:
        - /var/lib/consul
        - /etc/consul.d
        - /etc/consul.d/config.json

    # TODO finish configuration
    - name: Start and enable consul service
      become: true
      ansible.builtin.systemd:
        name: consul
        enabled: true
        state: started
