- hosts: "servers"
  name: add users
  become: yes
  tasks:
    - name: add user
      ansible.builtin.user:
        name: "{{user_name}}"
        shell: /bin/bash
        create_home: yes
    - name: add user to sudo
      ansible.builtin.user:
        name: "{{user_name}}"
        groups: sudo
        append: yes
    - name: create ssh catalog
      ansible.builtin.file:
        path: /home/{{user_name}}/.ssh
        state: directory
        mode: '0700'
        owner: "{{user_name}}"
        group: "{{user_name}}"
    - name: add public key
      ansible.builtin.copy:
        dest: /home/{{user_name}}/.ssh/authorized_keys
        content: "{{user_ssh_key}}"
        owner: "{{user_name}}"
        group: "{{user_name}}"
        mode: '0600'
    