# https://docs.docker.com/engine/install/ubuntu/
- name: install docker
  hosts: servers
  tasks:
    - name: update apt
      become: true
      ansible.builtin.command:
        cmd: apt update

    - name: install curl certificates
      become: true
      ansible.builtin.command:
        cmd: apt-get install ca-certificates curl -y

    - name: install keyrings
      become: true
      ansible.builtin.command:
        cmd: install -m 0755 -d /etc/apt/keyrings

    - name: download gpg keys
      become: true
      ansible.builtin.command:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

    - name: change mode to 
      become: true
      ansible.builtin.command:
        cmd: chmod a+r /etc/apt/keyrings/docker.asc

    - name: add docker repo to apt
      become: true
      ansible.builtin.shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: update apt again
      become: true
      ansible.builtin.command:
        cmd: apt update

    - name: install docker
      become: true
      ansible.builtin.command:
        cmd: apt install docker.io -y

    - name: install docker-compose
      become: true
      ansible.builtin.command:
        cmd: apt install docker-compose -y

    - name: enable using docker to non-root user
      become: true
      ansible.builtin.command:
        cmd: chmod 666 /var/run/docker.sock