- name: install docker
  hosts: servers
  tasks:
    - name: update
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: install docker
      become: true
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: install docker-compose
      become: true
      ansible.builtin.apt:
        name: docker-compose
        state: present

    - name: enable using docker to non-root user
      become: true
      ansible.builtin.file:
        path: /var/run/docker.sock
        mode: "{{ the_number_of_the_beast }}"
