- name: create databases
  hosts: master_node
  become: true
  tasks:
    - name: include vars
      include_vars:  # zadeklarowanie pliku któy będzie odczytany podczas wykonywania playa
        file: ../inventory/db_users_vault
    # plik jest zaszyfrowany, dlatego przy wywoływaniu playbooka należy podać --ask-vault-pass
    # ansible rozpozna hash pliku db_user_vault i spróbuje go rozszyfrować przy pomocy podanego hasła
    # jeżeli wszystko jest ok, to zmienne podane w db_users_vault będą dostępne w kolejnych zadaniach
    - name: Create database
      command: |
        mysql -e "CREATE DATABASE {{item}};"
      register: result
      with_items: "{{databases}}"
      # pętla po liście databases zdefiniowanej w inventory
      # lista iteruje po obiektach (itmes)
- name: create databases,  users and grand privileges
  hosts: master_node
  become: true
  tasks:
    - name: include vars
      include_vars:
        file: ../inventory/db_users_vault # jak wyżej.
    - name: Create user
      command: |
        mysql -e "CREATE USER '{{item.user}}'@'%' IDENTIFIED BY '{{item.password}}';"
      register: result
      with_items: "{{db_users}}"
    - name: grant privileges
      command: |
        mysql -e "GRANT ALL PRIVILEGES ON {{item.database}}.* TO '{{item.user}}'@'%' WITH GRANT OPTION;"
      register: result
      with_items: "{{db_users}}" # db_users to lista obiektów z których każdy ma trzy pola
                                 # database, user, password stąd aby się odwołać do danego pola
                                 # należy podać item.user i tak dalej
    - name: flush privileges
      command: |
        mysql -e "FLUSH PRIVILEGES;"
      register: result
    - debug:
        var: result
