- name: MariaDB install  #nazwa playa
  hosts: 'db_servers'  # grupa hostów lub nazwa hosta na których będzie wykonywany
  become: true # podniesienie uprawnień
  tasks:
    - name: install maria db  
      become: yes
      expect: # wykonanie polecenia ze przewidywanym propmptem do potwierdzenia
        command: 'apt install mariadb-server'
        responses:
          '.*continue?.*': 'Y' # 'Do you want to continue? [Y/n]''  # odpowiedź na pytanie.
          # odpowiedź na pytanie jest wybierana na podstawie regexa w tym przypadku: '.*continue.*'
          # uwaga: regexy są sprawdzane przez pythona
    - name: mariaDB secure instalation
      become: yes
      expect:
        command: 'sudo mysql_secure_installation'
        responses: # jak wyżej tylko że więcej propmtów
          password: "{{root_password}}" 
          '.*password for root.*': '' # 'Enter current password for root \(enter for none\)\:'
          '.*root password.*' : 'N' # 'Set root password? \[Y\/n\]'
          '.*anonymous.*' : 'Y' # 'Remove anonymous users? \[Y\/n\] '
          '.*root login.*' : 'Y' # 'Disallow root login remotely? \[Y\/n\]'
          '.*test database.*' : 'Y' # 'Remove test database and access to it? \[Y\/n\]'
          '.*privilege tables.*' : 'Y' # 'Reload privilege tables now? \[Y\/n\]'
- name: configure mariadb
  hosts: db_servers
  tasks:
    - name: bind ports
      become: yes
      blockinfile: # block in file umieszczenie większej ilości tesktu w pliku podanym w dest
        dest: /etc/mysql/my.cnf
        block: | # po rurce enter i tekst piszemy jak w notantiku od wcięcia za blok
          [mysqld]
          bind-address=0.0.0.0
- name: restart maria db
  hosts: db_servers
  tasks:
    - name: restart maria db
      become: yes
      command: systemctl restart mariadb
