---
- name: run cadvisor on linux machine
  hosts: all
  become: yes
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /tmp/cadvisor
        state: directory
        mode: '0755'

    - name: Copy docker compose to location
      copy:
        src: docker-compose.yml
        dest: /tmp/cadvisor/docker-compose.yml

    # it is hack, should use newer version of ansible and community docker module
    - name: create shell script to run docker 
      copy:
        dest: /tmp/cadvisor/run_docker_compose.sh
        content: |
          #!/bin/bash
          docker-compose -f /tmp/cadvisor/docker-compose.yml up -d

    - name: Run shell script on remote server
      shell: sh /tmp/cadvisor/run_docker_compose.sh
    
    - name: add cadvisor exporter configuration
      become: yes
      blockinfile: 
        dest: /etc/prometheus/prometheus.yml
        marker: "# {mark} ANSIBLE MANAGED BLOCK cadvisor exporter"
        block: |2
            - job_name: cadvisor
              static_configs:
                - targets: ['localhost:8081']

    - name: restart prometheus
      systemd:
        name: prometheus
        enabled: yes
        state: restarted