---
- name: Install Node Exporter
  hosts: all
  become: true

  tasks:
    - name: Add monitoring user group
      ansible.builtin.group:
        name: "{{ grafana_user_group }}"
        state: present

    - name: Add grafana user in grafana group
      ansible.builtin.user:
        name: "{{ node_exporter_user }}"
        group: "{{ grafana_user_group }}"
        shell: /usr/sbin/nologin
        system: true

    - name: Download Node Exporter
      ansible.builtin.get_url:
        url: "{{ node_exporter_release }}"
        dest: /tmp/node_exporter.tar.gz
        owner: "{{ node_exporter_user }}"
        group: "{{ grafana_user_group }}"
        mode: '0755'

    - name: Extract Node Exporter
      ansible.builtin.unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp/
        remote_src: true

    - name: Copy Node Exporter binary to /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/node_exporter-1.5.0.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        owner: "{{ node_exporter_user }}"
        group: "{{ grafana_user_group }}"
        mode: '0755'
        remote_src: true
      become: true

    - name: Remove original Node Exporter binary
      ansible.builtin.file:
        path: /tmp/node_exporter-1.5.0.linux-amd64/node_exporter
        state: absent
      become: true

    - name: Create node exporter systemd service
      ansible.builtin.copy:
        src: node_exporter_service.ini
        dest: /etc/systemd/system/node_exporter.service
        owner: "{{ node_exporter_user }}"
        group: "{{ grafana_user_group }}"
        mode: '0644'

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start and enable Node Exporter service
      ansible.builtin.systemd:
        name: node_exporter
        enabled: true
        state: started

    - name: Add node exporter configuration
      become: true
      ansible.builtin.blockinfile:
        dest: /etc/prometheus/prometheus.yml
        marker: "# {mark} ANSIBLE MANAGED BLOCK node exporter"
        block: |2
            - job_name: node_export
              static_configs:
                - targets: ['localhost:9100']

    - name: Restart prometheus
      ansible.builtin.systemd:
        name: prometheus
        enabled: true
        state: restarted
