# Playbook for Ubuntu 20.04
# Adapted from https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-20-04
- name: Install Elasticsearch
  hosts: servers
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - gnupg
          - curl
        state: present
        update_cache: true

    - name: Download Elasticsearch public GPG key
      ansible.builtin.get_url:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        dest: /usr/share/keyrings/elasticsearch-keyring.gpg
        mode: '0644'

    - name: Add Elasticsearch repository to sources list
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/elastic-7.x.list
        line: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/7.x/apt stable main"
        create: true
        mode: '0644'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Elasticsearch
      ansible.builtin.apt:
        name: elasticsearch
        state: present

    - name: Configure Elasticsearch to listen on localhost
      ansible.builtin.lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        line: "network.host: localhost"
        create: true
        mode: '0644'

    - name: Ensure Elasticsearch is running and enabled on boot
      ansible.builtin.service:
        name: elasticsearch
        enabled: true
        state: started

# totally remove:
# systemctl stop elasticsearch.service
# apt-get remove --purge elasticsearch
# rm -rf /etc/elasticsearch
# rm -rf /var/lib/elasticsearch
