# Playbook for Ubuntu 20.04
# Adapted from https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/#std-label-install-mdb-community-ubuntu
- name: MongoDB install
  hosts: servers
  become: true
  tasks:
    - name: Install curl
      ansible.builtin.apt:
        name: gnupg,curl
        state: present

    - name: Download the MongoDB public GPG key
      ansible.builtin.get_url:
        url: https://www.mongodb.org/static/pgp/server-7.0.asc
        dest: /tmp/mongodb-server-7.0.asc
        mode: '0644'

    - name: Convert the GPG key to keyring format
      ansible.builtin.command:
        cmd: gpg --output /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor /tmp/mongodb-server-7.0.asc
        creates: /usr/share/keyrings/mongodb-server-7.0.gpg

    - name: Remove temporary key file
      ansible.builtin.file:
        path: /tmp/mongodb-server-7.0.asc
        state: absent

    - name: Add MongoDB repository to sources list
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/mongodb-org-7.0.list
        line: |
          deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ]
          https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse
        create: true
        mode: '0644'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install MongoDB
      ansible.builtin.apt:
        name: mongodb-org
        state: present
        update_cache: true

    - name: Ensure mongodb is running and and enabled to start automatically on reboots
      ansible.builtin.service:
        name: mongod
        enabled: true
        state: started

# totally remove:
# systemctl stop mongod.service
# apt-get purge "mongodb-org*"
# rm -r /var/log/mongodb
# rm -r /var/lib/mongodb
