# Playbook for Ubuntu 20.04
# Adapted from https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/#std-label-install-mdb-community-ubuntu
- name: MongoDB install
  hosts: servers
  become: yes
  tasks:
    - name: install curl
      ansible.builtin.command: |
        apt-get install gnupg curl -y
    - name: Import the MongoDB public GPG key and save to keyring
      ansible.builtin.shell: |
        curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | \
        gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor

    - name: update source list
      ansible.builtin.shell: |
        echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
    
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
    
    - name: Install MongoDB
      ansible.builtin.apt:
        name: mongodb-org
        state: present
        update_cache: yes
    
    - name: Ensure mongodb is running and and enabled to start automatically on reboots
      ansible.builtin.service: 
        name: mongod 
        enabled: yes
        state: started

# totally remove:
# systemctl stop mongod.service
# apt-get purge "mongodb-org*"
# rm -r /var/log/mongodb
# rm -r /var/lib/mongodb
