---
- name: Run cAdvisor on linux machine
  hosts: all
  become: true
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /tmp/cadvisor
        state: directory
        mode: '0755'

    - name: Copy docker compose to location
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: /tmp/cadvisor/docker-compose.yml
        owner: root
        group: root
        mode: '0644'
# TODO create user for docker

    # it is hack, should use newer version of ansible and community docker module
    - name: Create shell script to run docker
      ansible.builtin.copy:
        dest: /tmp/cadvisor/run_docker_compose.sh
        content: |
          #!/bin/bash
          docker-compose -f /tmp/cadvisor/docker-compose.yml up -d
        owner: root
        group: root
        mode: '0644'

    - name: Run shell script on remote server
      ansible.builtin.script:
        src: /tmp/cadvisor/run_docker_compose.sh
      become: true

    - name: Add cadvisor exporter configuration
      become: true
      ansible.builtin.blockinfile:
        dest: /etc/prometheus/prometheus.yml
        marker: "# {mark} ANSIBLE MANAGED BLOCK cadvisor exporter"
        block: |2
            - job_name: cadvisor
              static_configs:
                - targets: ['localhost:8081']

    - name: Restart prometheus
      ansible.builtin.systemd:
        name: prometheus
        enabled: true
        state: restarted
