---
- name: Install Grafana
  hosts: all
  become: true

  tasks:
    - name: Add APT key
      ansible.builtin.apt_key:
        url: "{{ grafana_gpg_key }}"
        state: present

    - name: Add Grafana APT repository
      ansible.builtin.apt_repository:
        repo: "deb {{ grafana_apt_repository }} stable main"
        state: present

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Grafana
      ansible.builtin.apt:
        name: grafana
        state: present

    - name: Setup grafana.ini
      ansible.builtin.lineinfile:
        path: /etc/grafana/grafana.ini
        regexp: '^;root_url = .*'
        line: 'root_url = %(protocol)s://%(domain)s:%(http_port)s/monitor/'
        backrefs: true

    - name: Start and enable Grafana service
      ansible.builtin.systemd:
        name: grafana-server
        enabled: true
        state: started

    - name: Backup default nginx config - copy
      ansible.builtin.copy:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-available/default.backup
        remote_src: true
        mode: '0644'

    - name: Backup default nginx config - remove original
      ansible.builtin.file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: Copy nginx new nginx config to sites-available
      ansible.builtin.copy:
        src: grafana_nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: '0644'

    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
