all:
  vars:
    kube_release: https://releases.hashicorp.com/consul/1.8.4/consul_1.8.4_linux_amd64.zip
     
  master_nodes:
    node_1m:
      ansible_host: <<node1_ip>>
      ansible_ssh_user: <<ssh_user>>
      server_name: node1-m
    
    node_2m:
      ansible_host: <<node2_ip>>
      ansible_ssh_user: <<ssh_user>>
      server_name: node2-m

  worker_nodes:
    node_1w:
      ansible_host: <<node1_ip>>
      ansible_ssh_user: <<ssh_user>>
      server_name: node1-w
    
    node_2w:
      ansible_host: <<node2_ip>>
      ansible_ssh_user: <<ssh_user>>
      server_name: node2-w
