---
# and https://computingforgeeks.com/install-and-configure-prometheus-mysql-exporter-on-ubuntu-centos/
- name: Install mysql/mariaDb Exporter
  hosts: all
  become: true
  tasks:
#     - name: Create mysql exporter user
#       ansible.builtin.user:
#         name: mysqld_exporter
#         shell: /bin/false
# # variables

#     - name: Create mysql user
#       ansible.builtin.command: |
#         mysql -e "CREATE USER 'mysqld_exporter'@'localhost' IDENTIFIED BY 'StrongPassword' WITH MAX_USER_CONNECTIONS 2;"
#       tags:
#         - skip_ansible_lint

#     - name: Add permissions
#       ansible.builtin.command: |
#         mysql -e "GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'mysqld_exporter'@'localhost';"
#       tags:
#         - skip_ansible_lint

#     - name: Flush
#       ansible.builtin.command: |
#         mysql -e "FLUSH PRIVILEGES;"
#       tags:
#         - skip_ansible_lint

#     - name: Create mysqld credentials
#       ansible.builtin.copy:
#         dest: /etc/.mysqld_exporter.cnf
#         content: |
#           [client]
#           user=mysqld_exporter
#           password=StrongPassword
#         owner: root
#         group: root
#         mode: '0644'

#     - name: Create my sql exporter systemd service
#       ansible.builtin.copy:
#         src: mysql_exporter_service.ini
#         dest: /etc/systemd/system/mysqld_exporter.service
#         owner: root
#         group: root
#         mode: '0644'

    - name: Download latest mysqld_exporter release
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/mysqld_exporter/releases/latest/download/mysqld_exporter-{{ mysql_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/mysqld_exporter.tar.gz
        mode: '0644'

    - name: Extract mysqld_exporter archive
      ansible.builtin.unarchive:
        src: /tmp/mysqld_exporter.tar.gz
        dest: /usr/local/bin/
        remote_src: true
        creates: /usr/local/bin/mysqld_exporter
# TODO fix this
    - name: Set executable permissions for mysqld_exporter
      ansible.builtin.file:
        path: mysqld_exporter-*.linux-amd64/mysqld_exporter
        mode: '0755'
      become: true

    - name: Copy mysql exporter binary to /usr/local/bin
      ansible.builtin.copy:
        src: mysqld_exporter-*.linux-amd64/mysqld_exporter
        dest: /usr/local/bin/mysqld_exporter
        owner: root
        group: root
        mode: '0755'
        remote_src: true
      become: true

    - name: Remove original mysql exporter binary
      ansible.builtin.file:
        path: mysqld_exporter-*.linux-amd64/mysqld_exporter
        state: absent
      become: true


    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start and enable mysql exporter service
      ansible.builtin.systemd:
        name: mysqld_exporter
        enabled: true
        state: started

    - name: Add node exporter configuration
      become: true
      ansible.builtin.blockinfile:
        dest: /etc/prometheus/prometheus.yml
        marker: "# {mark} ANSIBLE MANAGED BLOCK mysql exporter 1"
        block: |2
            - job_name: mysql_export
              static_configs:
                - targets: ['localhost:9104']

    - name: Restart prometheus
      ansible.builtin.systemd:
        name: prometheus
        enabled: true
        state: restarted
