---
# and https://computingforgeeks.com/install-and-configure-prometheus-mysql-exporter-on-ubuntu-centos/
- name: Install mysql/mariaDb Exporter
  hosts: all
  become: yes
  tasks:
    - name: Create mysql exporter user
      ansible.builtin.user:
        name: mysqld_exporter
        shell: /bin/false
    #variables
    - name: create mysql user
      ansible.builtin.command: |
        mysql -e "CREATE USER 'mysqld_exporter'@'localhost' IDENTIFIED BY 'StrongPassword' WITH MAX_USER_CONNECTIONS 2;"

    - name: add permissions
      ansible.builtin.command: |
        mysql -e "GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'mysqld_exporter'@'localhost';"

    - name: flush
      ansible.builtin.command: |
        mysql -e "FLUSH PRIVILEGES;"

    - name: create mysqld credentials
      ansible.builtin.copy:
        dest: /etc/.mysqld_exporter.cnf
        content: |
          [client]
          user=mysqld_exporter
          password=StrongPassword

    - name: Create my sql exporter systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/mysqld_exporter.service
        content: |
          [Unit]
          Description=Prometheus MySQL Exporter
          After=network.target
          User=prometheus
          Group=prometheus

          [Service]
          Type=simple
          Restart=always
          ExecStart=/usr/local/bin/mysqld_exporter \
          --config.my-cnf /etc/.mysqld_exporter.cnf \
          --web.listen-address=0.0.0.0:9104

          [Install]
          WantedBy=multi-user.target

    - name: download latest exporter 
      ansible.builtin.shell: |
        curl -s https://api.github.com/repos/prometheus/mysqld_exporter/releases/latest   | grep browser_download_url | grep linux-amd64 |  cut -d '"' -f 4 | wget -qi -

    - name: extract 
      ansible.builtin.shell: |
        tar xvf mysqld_exporter-*.linux-amd64.tar.gz

    - name: chmod as exec 
      ansible.builtin.shell: |
        chmod +x mysqld_exporter-*.linux-amd64/mysqld_exporter

    - name: Move mysql exporter binary
      ansible.builtin.command: >
        mv mv mysqld_exporter-*.linux-amd64/mysqld_exporter /usr/local/bin

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable mysql exporter service
      ansible.builtin.systemd:
        name: mysqld_exporter
        enabled: yes
        state: started

    - name: add node exporter configuration
      become: yes
      ansible.builtin.blockinfile: 
        dest: /etc/prometheus/prometheus.yml
        marker: "# {mark} ANSIBLE MANAGED BLOCK mysql exporter 1"
        block: |2
            - job_name: mysql_export
              static_configs:
                - targets: ['localhost:9104']

    - name: restart prometheus
      ansible.builtin.systemd:
        name: prometheus
        enabled: yes
        state: restarted
