---
- name: Install Node Exporter
  hosts: all
  become: yes

  tasks:
    - name: Create Node Exporter user
      ansible.builtin.user:
        name: node_exporter
        shell: /bin/false

    - name: Download Node Exporter
      ansible.builtin.get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: Extract Node Exporter
      ansible.builtin.unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move Node Exporter binary
      ansible.builtin.command: >
        mv /tmp/node_exporter-1.5.0.linux-amd64/node_exporter /usr/local/bin/
      become: yes

    - name: Create Node Exporter systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable Node Exporter service
      ansible.builtin.systemd:
        name: node_exporter
        enabled: yes
        state: started
    - name: add node exporter configuration
      become: yes
      ansible.builtin.blockinfile: 
        dest: /etc/prometheus/prometheus.yml
        marker: "# {mark} ANSIBLE MANAGED BLOCK node exporter"
        block: |2
            - job_name: node_export
              static_configs:
                - targets: ['localhost:9100']

    - name: restart prometheus
      ansible.builtin.systemd:
        name: prometheus
        enabled: yes
        state: restarted