- name: Create databases
  hosts: servers
  become: true
  tasks:
    - name: Create database
      ansible.builtin.command: |
        mysql -e "CREATE DATABASE {{ item.database }};"
      register: result
      with_items: "{{ databases }}"
      tags:
        - skip_ansible_lint

- name: Create databases, users and grant privileges
  hosts: servers
  become: true
  tasks:
    - name: Create user
      ansible.builtin.command: |
        mysql -e "CREATE USER '{{ item.user }}'@'%' IDENTIFIED BY '{{ item.password }}';"
      register: result
      with_items: "{{ databases }}"
      tags:
        - skip_ansible_lint

    - name: Grant privileges
      ansible.builtin.command: |
        mysql -e "GRANT ALL PRIVILEGES ON {{ item.database }}.* TO '{{ item.user }}'@'%' WITH GRANT OPTION;"
      register: result
      with_items: "{{ databases }}"
      tags:
        - skip_ansible_lint

    - name: Flush privileges
      ansible.builtin.command: |
        mysql -e "FLUSH PRIVILEGES;"
      register: result
      tags:
        - skip_ansible_lint

    - name: Debug
      ansible.builtin.debug:
        var: result
