- name: create databases
  hosts: servers
  become: true
  tasks:
    - name: Create database
      command: |
        mysql -e "CREATE DATABASE {{item.database}};"
      register: result
      with_items: "{{databases}}"
- name: create databases, users and grand privileges
  hosts: servers
  become: true
  tasks:
    - name: Create user
      command: |
        mysql -e "CREATE USER '{{item.user}}'@'%' IDENTIFIED BY '{{item.password}}';"
      register: result
      with_items: "{{databases}}"
    - name: grant privileges
      command: |
        mysql -e "GRANT ALL PRIVILEGES ON {{item.database}}.* TO '{{item.user}}'@'%' WITH GRANT OPTION;"
      register: result
      with_items: "{{databases}}"
    - name: flush privileges
      command: |
        mysql -e "FLUSH PRIVILEGES;"
      register: result
    - debug:
        var: result
