---
- name: Install Prometheus
  hosts: "servers"
  become: true
  tasks:
    - name: Create Prometheus user
      ansible.builtin.user:
        name: prometheus
        shell: /bin/false

    - name: Download Prometheus
      ansible.builtin.get_url:
        url: "{{ prometheus_release }}"
        dest: /tmp/prometheus.tar.gz
        owner: root
        group: root
        mode: '0755'

    - name: Extract Prometheus
      ansible.builtin.unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp/
        remote_src: true

    - name: Copy Prometheus binary to /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/prometheus-2.44.0.linux-amd64/prometheus
        dest: /usr/local/bin/prometheus
        owner: root
        group: root
        mode: '0755'
        remote_src: true
      become: true

    - name: Remove original Prometheus binary
      ansible.builtin.file:
        path: /tmp/prometheus-2.44.0.linux-amd64/prometheus
        state: absent
      become: true

    - name: Copy Promtool binary to /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/prometheus-2.44.0.linux-amd64/promtool
        dest: /usr/local/bin/promtool
        owner: root
        group: root
        mode: '0755'
        remote_src: true
      become: true

    - name: Remove original Promtool binary
      ansible.builtin.file:
        path: /tmp/prometheus-2.44.0.linux-amd64/promtool
        state: absent
      become: true

    - name: Create Prometheus directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Copy Prometheus config to /etc/prometheus
      ansible.builtin.copy:
        src: /tmp/prometheus-2.44.0.linux-amd64/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        owner: root
        group: root
        mode: '0644'
        remote_src: true
      become: true

    - name: Remove original Prometheus config
      ansible.builtin.file:
        path: /tmp/prometheus-2.44.0.linux-amd64/prometheus.yml
        state: absent
      become: true

    - name: Create Prometheus systemd service
      ansible.builtin.copy:
        src: prometheus_service.ini
        dest: /etc/systemd/system/prometheus.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start and enable Prometheus service
      ansible.builtin.systemd:
        name: prometheus
        enabled: true
        state: started
