---
- name: run jaeger all in one 
  hosts: all
  become: yes
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /tmp/jaeger
        state: directory
        mode: '0755'

    - name: Copy docker compose to location
      copy:
        src: docker-compose.yml
        dest: /tmp/jaeger/docker-compose.yml

    # it is hack, should use newer version of ansible and community docker module
    - name: create shell script to run docker 
      copy:
        dest: /tmp/jaeger/run_docker_compose.sh
        content: |
          #!/bin/bash
          docker-compose -f /tmp/jaeger/docker-compose.yml up -d

    - name: Run shell script on remote server
      shell: sh /tmp/jaeger/run_docker_compose.sh