- hosts: "servers"
  name: install docker
  tasks:
    - name: update
      become: yes
      command: |
        apt update
    - name: install docker
      become: yes
      command: |
        apt install docker.io -y
    - name: install docker-compose
      become: yes
      command: |
        apt install docker-compose -y
    - name: enable using docker to none root user
      become: yes
      command: |
        sudo chmod "{{the_number_of_the_beast}}" /var/run/docker.sock