---
- name: Install Grafana
  hosts: all
  become: yes

  tasks:
    - name: Add APT key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Grafana
      apt:
        name: grafana
        state: present
        
    - name: setup grafana.ini
      lineinfile:
        path: /etc/grafana/grafana.ini
        regexp: '^;root_url = .*'
        line: 'root_url = %(protocol)s://%(domain)s:%(http_port)s/monitor/'
        backrefs: yes

    - name: Start and enable Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started

    - name: backup default nginx config
      command: mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
    
    - name: Copy nginx new nginx config to sites-available
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
