services:
    rabbitmq:
        image: rabbitmq:3.9-management
        ports:
            - "5672:5672"
            - "15672:15672"
    redis:
        image: redis:6.2
        ports:
            - "6379:6379"
    mssql:
        image: mcr.microsoft.com/mssql/server:2019-CU11-ubuntu-20.04
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=veryStrongPassword!23
            - MSSQL_PID=Express
            - MSSQL_COLLATION=Polish_CI_AS
        volumes:
            - articles-mssql-test:/var/opt/mssql
volumes:
    articles-mssql-test:

# connextions string:
# "Data Source=localhost;Initial Catalog=dbName;User Id=SA;Password=veryStrongPassword!23;Trust Server Certificate=true"

#rabbitmq http://localhost:15672/  user&pass: guest

