# based on https://www.atlantic.net/vps-hosting/how-to-install-consul-server-on-ubuntu/
- hosts: "all"
  name: install consul cluster
  tasks:
    - name: update apt
      become: yes
      command: |
        apt update
    
    - name: Install unzip gnupg2 curl wget
      become: yes
      apt:
        name:
          - unzip
          - gnupg2
          - curl
          - wget
        state: present
        update_cache: yes

    - name: Download consul release
      get_url:
        url: "{{consul_release}}"
        dest: /tmp/{{consul_zip_file}}

    - name: Extract
      unarchive:
        src: /tmp/{{consul_zip_file}}
        dest: /tmp/
        remote_src: yes

    - name: Move binaries
      command: >
        mv /tmp/{{consul_file}} /usr/local/bin/
      become: yes

    - name: Create consul group
      become: yes
      group:
        name: "{{ consul_group }}"
        state: present

    - name: Create consul user
      become: yes
      user:
        name: "{{ consul_user }}"
        group: "{{ consul_group }}"
        state: present
        createhome: yes
        home: /home/{{ consul_user }}
        shell: /bin/bash

    - name: Create directories
      become: yes
      file:
        dest: "{{ item }}"
        state: directory
      with_items:
        - /var/lib/consul
        - /etc/consul.d

    - name: create systemd service file
      become: yes
      ansible.builtin.template:
        src: ./templates/consul.service.j2
        dest: /etc/systemd/system/consul.service

    - name: Reload systemd
      become: yes
      systemd:
        daemon_reload: yes

    - name: create consul.json file
      become: yes
      ansible.builtin.template:
        src: ./templates/config.j2
        dest: /etc/consul.d/config.json

    - name: change owner for created directories and files
      become: yes
      file:
        path: "{{ item }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: '755'
      with_items: 
        - /var/lib/consul
        - /etc/consul.d
        - /etc/consul.d/config.json

    - name: Start and enable consul service
      become: yes
      systemd:
        name: consul
        enabled: yes
        state: started