# based on https://www.atlantic.net/vps-hosting/how-to-install-consul-server-on-ubuntu/
- name: install consul cluster
  hosts: all
  tasks:
    - name: Install unzip gnupg2 curl wget
      become: true
      ansible.builtin.apt:
        name:
          - unzip
          - gnupg2
          - curl
          - wget
        state: present
        update_cache: true
      changed_when: false

    - name: Download consul release
      ansible.builtin.get_url:
        url: "{{ consul_release }}"
        dest: /tmp/{{ consul_zip_file }}
      changed_when: false

    - name: Extract
      ansible.builtin.unarchive:
        src: /tmp/{{ consul_zip_file }}
        dest: /tmp/
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: '755'
        remote_src: true
      changed_when: false

    - name: Copy consul binary to /usr/local/bin
      become: true
      ansible.builtin.copy:
        src: /tmp/{{ consul_file }}
        dest: /usr/local/bin/{{ consul_file }}
        mode: '0755'

    - name: Remove consul binary from /tmp
      become: true
      ansible.builtin.file:
        path: /tmp/{{ consul_file }}
        state: absent

    - name: Create consul group
      become: true
      ansible.builtin.group:
        name: "{{ consul_group }}"
        state: present
      changed_when: false

    - name: Create consul user
      become: true
      ansible.builtin.user:
        name: "{{ consul_user }}"
        group: "{{ consul_group }}"
        state: present
        createhome: true
        home: /home/{{ consul_user }}
        shell: /bin/bash
      changed_when: false

    - name: Create directories
      become: true
      ansible.builtin.file:
        dest: "{{ item }}"
        state: directory
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: '755'
      with_items:
        - /var/lib/consul
        - /etc/consul.d
      changed_when: false

    - name: create systemd service file
      become: true
      ansible.builtin.template:
        src: ./templates/consul.service.j2
        dest: /etc/systemd/system/consul.service
      changed_when: false

    - name: Reload systemd
      become: true
      ansible.builtin.systemd:
        daemon_reload: true
      changed_when: false

    - name: create consul.json file
      become: true
      ansible.builtin.template:
        src: ./templates/config.j2
        dest: /etc/consul.d/config.json
      changed_when: false

    - name: change owner for created directories and files
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: '755'
      with_items:
        - /var/lib/consul
        - /etc/consul.d
        - /etc/consul.d/config.json
      changed_when: false

    - name: Start and enable consul service
      become: true
      ansible.builtin.systemd:
        name: consul
        enabled: true
        state: started
      changed_when: false
# TODO check file permisions
