all:
  vars:
    consul_release: https://releases.hashicorp.com/consul/1.8.4/consul_1.8.4_linux_amd64.zip
    consul_zip_file: consul_1.8.4_linux_amd64.zip
    consul_file: consul
    consul_user: consul
    consul_group: consul
    consul_encrypt_key: <<key>>
    log_level: "INFO"
    data_center: "dc0"
    ports:
      - port: 8600
        direction: inbound
        name: "DNS Server"

      - port: 8501
        direction: inbound
        name: "HTTPS API"
      
      - port: 8503
        direction: inbound
        name: "gRPC API"

      - port: 8300
        direction: inbound
        name: "Server RPC-In"

      - port: 8300
        direction: outbound
        name: "Server RPC-Out"

      - port: 8301
        direction: inbound
        name: "LAN-Serf-In"

      - port: 8301
        direction: outbound
        name: "LAN-Serf-Out"

      - port: 8302
        direction: inbound
        name: "WAN-Serf-In"

      - port: 8302
        direction: outbound
        name: "WAN-Serf-Out"
    
  hosts:
    node_1:
      ansible_host: <<node1_ip>>
      ansible_ssh_user: <<ssh_user>>
      server_name: node1
      consul_retry_join: ["<<node2_ip>>"] # other servers ips
      node_name: n1
      is_server: "true" # must be a string
      bind_addr: 0.0.0.0 # do not use on production
    
    node_2:
      ansible_host: <<node2_ip>>
      ansible_ssh_user: <<ssh_user>>
      server_name: node2
      consul_retry_join: ["<<node1_ip>>"]
      node_name: n2
      is_server: "true"
      bind_addr: 0.0.0.0
