all:
  vars:
    consul_release: https://releases.hashicorp.com/consul/1.8.4/consul_1.8.4_linux_amd64.zip
    consul_zip_file: consul_1.8.4_linux_amd64.zip
    consul_file: consul
    consul_user: consul
    consul_group: consul
    consul_encrypt_key: <<key>>
    log_level: "INFO"
    datacenter: "dc1"
    
  hosts:
    node_1:
      ansible_host: <<node1_ip>>
      ansible_ssh_user: <<ssh_user>>
      server_name: node1
      consul_retry_join: ["<<node2_ip>>"] # other servers ips
      node_name: n1
      is_server: "true" # must be a string
      bind_addr: 0.0.0.0 # do not use on production
    
    node_2:
      ansible_host: <<node2_ip>>
      ansible_ssh_user: <<ssh_user>>
      server_name: node2
      consul_retry_join: ["<<node1_ip>>"]
      node_name: n2
      is_server: "true"
      bind_addr: 0.0.0.0
