- name: install consul cluster
  hosts: all
  tasks:
    - name: generate ip table backup file name
      ansible.builtin.set_fact:
        file_name: "IP_tables_backup_{{ ansible_date_time.year }}_{{ ansible_date_time.month }}_{{ ansible_date_time.day }}_{{ ansible_date_time.hour }}_{{ ansible_date_time.minute }}.txt"
    
    - name: backup existing rules
      become: yes
      ansible.builtin.shell: iptables-save > "{{ file_name }}"
      
    - name: set rules
      become: yes
      ansible.builtin.shell: "iptables -A {{ item.direction }} -p tcp --dport  {{ item.port }} -j ACCEPT"
      loop: "{{ ports }}"