# Playbook for Ubuntu 20.04
# based on https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-redis-on-ubuntu-20-04
- name: Install redis
  hosts: servers
  become: true
  tasks:
    - name: Install curl
      ansible.builtin.apt:
        name:
          - gnupg
          - curl
        state: present
        update_cache: true

    - name: Install redis
      ansible.builtin.apt:
        name: redis-server
        state: present
        update_cache: true

    - name: Set superviser
      ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        line: "supervised systemd"

    - name: Ensure redis is running and enabled to start automatically on reboots
      ansible.builtin.service:
        name: redis
        enabled: true
        state: started
