---
- name: run mssql container
  hosts: all
  become: yes
  tasks:
    - name: Create a temporary directory if it does not exist
      ansible.builtin.file:
        path: /tmp/mssql
        state: directory
        mode: '0755'

    - name: Copy docker compose to location
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: /tmp/mssql/docker-compose.yml

    # it is hack, should use newer version of ansible and community docker module
    - name: create shell script to run docker 
      ansible.builtin.copy:
        dest: /tmp/mssql/run_docker_compose.sh
        content: |
          #!/bin/bash
          docker-compose -f /tmp/mssql/docker-compose.yml up -d

    - name: Run shell script on remote server
      ansible.builtin.shell: sh /tmp/mssql/run_docker_compose.sh