services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2019-CU11-ubuntu-20.04
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=P@ssw0rd
            - MSSQL_PID=Express
            - MSSQL_COLLATION=Polish_CI_AS
        volumes:
            - volume-mssql-test:/var/opt/mssql
volumes:
    volume-mssql-test: