- name: Install certbot and secure basic
  hosts: servers
  tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Install Python and dependencies
      become: true
      ansible.builtin.apt:
        name:
          - python3
          - python3-venv
          - libaugeas0
        state: present
        update_cache: true

    - name: Install certbot
      become: true
      ansible.builtin.shell: |
        /opt/certbot/bin/pip install certbot certbot-apache certbot-nginx --upgrade --no-deps
      args:
        creates: /opt/certbot/bin/certbot

    - name: Link files
      become: true
      ansible.builtin.file:
        src: /opt/certbot/bin/certbot
        dest: /usr/bin/certbot
        state: link

    - name: Install certbot for nginx
      become: true
      ansible.builtin.expect:
        command: 'certbot --nginx'
        responses:
          '.*email address.*': '{{ email_address }}' # 'Enter email address for urgent renewal and security notices...'
          '.*read the Terms.*': 'Y' # 'Please read the Terms of Service at....? \[Y\/n\]'
          '.*share your email.*': 'N' # 'as if you want to share your email with EFF  \[Y\/n\] '
          '.*activate HTTPS for.*': '' # 'generate cert for all domains \[Y\/n\]'

    - name: Create shell script renew certificate
      ansible.builtin.copy:
        dest: /etc/cron.weekly/certbot.sh
        content: |
          #!/bin/sh
          /usr/bin/certbot renew > /dev/null 2>&1
          systemctl restart nginx
        mode: '0755'  # (rwxr-xr-x)
