- hosts: "servers"
  name: install nginx
  tasks:
    - name: Update and upgrade apt packages
      become: true
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
    - name: install nginx
      become: true
      ansible.builtin.apt:
        name: nginx
        state: latest
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
    - name: enable nginx
      become: yes
      ansible.builtin.command: |
        sudo systemctl enable nginx