- name: install nginx
  hosts: servers
  tasks:
    - name: Update and upgrade apt packages
      become: true
      ansible.builtin.apt:
        upgrade: true
        update_cache: true

    - name: install nginx
      become: true
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started

    - name: enable nginx
      become: true
      ansible.builtin.service:
        name: nginx
        enabled: true
