name: Ansible Lint

on: 
  pull_request:
  push:
    branches:
      - main
      - consul-lint-fixes

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install ansible-lint
        run: pip install ansible ansible-lint

      - name: Run ansible-lint for basics jobs
        run: ansible-lint ansible/basics/

      - name: Run ansible-lint for consul
        run: ansible-lint ansible/consul/ 
