# based on https://www.atlantic.net/vps-hosting/how-to-install-consul-server-on-ubuntu/  (Step 4)
- name: Install certbot and secure basic
  hosts: "servers"
  tasks:
    - name: Check nginx install
      ansible.builtin.command: which nginx
      register: nginx_installed
      ignore_errors: true

    - name: Exit if there is no nginx on server
      ansible.builtin.fail:
        msg: "Nginx is not installed run nginx install playbook first, or install nginx manually"
      when: nginx_installed.rc != 0

    - name: Copy nginx config file
      ansible.builtin.copy:
        src: /files/consul.conf
        dest: /etc/nginx/sites-available/consul.conf
    
    - name: Link conf file
      ansible.builtin.command: >
        ln -s /etc/nginx/sites-available/consul.conf /etc/nginx/sites-enabled/
      become: true

    - name: Restart nginx
      ansible.builtin.systemd:
        name: nginx
        enabled: yes
        state: restarted